version: '3'
services:
  redis:
    image: redis:5.0.3-alpine
    command: redis-server --requirepass "$REDIS_PASS"
    ports:
      - 6379
    environment:
      - REDIS_PASS=${REDIS_PASS}
  app:
    build: .
    command: sh -c "npm install && npm run lint && npm run clean && npm run build && npm run dev"
    working_dir: /usr/app/
    depends_on:
      - redis
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    environment:
      - APP_SERVER_PORT=8080
      - APP_REDIS=redis://:${REDIS_PASS}@redis:6379/0
      - APP_SERVER_BASE=${APP_SERVER_BASE}
      - APP_SESSION_SECRET=${APP_SESSION_SECRET}
      - APP_GH_CLIENTID=${APP_GH_CLIENTID}
      - APP_GH_SECRET=${APP_GH_SECRET}
